platform :ios, '12.0'

target 'VidLoaderExample' do
  use_frameworks!

  # pod 'VidLoader', :git => 'https://github.com/Cyklet/VidLoader.git'
  # pod 'VidLoader', :git => 'https://github.com/yavuzslmtpl/VidLoader.git'
  pod 'VidLoader', :path => '../'

end
